### PR TITLE
Add 4k support for xbox series x and xbox one x

### PR DESCRIPTION
**Pull request by seskid**
I have tested this on xbox series x but didnt have xbox one x to test. Since it doesn't have 4k swapchain limitations I assume xbox one x would work also.

### CODE REVIEW

**Comment by TheElixZammuto** [comment]
Hi,
I see that the PR adds support for H265 codec. While this is definetly a welcome addition, I don't get how this should fix the 4K TV resolution

**Comment by seskid** [comment]
> Hi, I see that the PR adds support for H265 codec. While this is definetly a welcome addition, I don't get how this should fix the 4K TV resolution

In my testing, the H265 codec was necessary when setting moonlight resolution to 4k.

**Comment by Nun-z** [comment]
I have taken a look at this.  With this, the stream will only launch without crashing with 1080p set for the host, but the stats are reporting a windows size of 3840x2160.  The screen is full size, not displaying in 1/4 of the screen, though the stats and logs are stuck in 1/4 of the screen.  I think it is 4k and I think it's working.

**Comment by seskid** [comment]
> I have taken a look at this. With this, the stream will only launch without crashing with 1080p set for the host, but the stats are reporting a windows size of 3840x2160. The screen is full size, not displaying in 1/4 of the screen, though the stats and logs are stuck in 1/4 of the screen. I think it is 4k and I think it's working.
> 
> Screenshot: https://ibb.co/RBNZ6XB

Thanks for testing! What system did you try on by chance? Was the hevc selected when choosing 4k resolution?

**Comment by Nun-z** [comment]
I tried it on an XSX.  It crashed when selecting 4k with either codec.

**Comment by seskid** [comment]
> I tried it on an XSX. It crashed when selecting 4k with either codec.

I gotcha. I wonder if this happens when the actual pc resolution is 1080p or less. When my pc is hooked 1440p monitor or 4k tv selecting moonlight 4k resolution worked for me.

**Comment by dtklein7** [comment]
I wonder if it has to do with available downscaling options on host machine's monitor. I think my 1440p monitor will take+downscale 4k content. Do y'all you know if your host machines can accept a 4k signal?

**Comment by seskid** [comment]
> I wonder if it has to do with available downscaling options on host machine's monitor. I think my 1440p monitor will take+downscale 4k content. Do y'all you know if your host machines can accept a 4k signal?

Yes this is true. If you set the xbox to the 4k resolution and the host machine resolution is not 1440p or 4k you will receive an options error from my testing. If the xbox is set to 1080p resolution it seems to downscale from 1440p or 4k or just match it of course if host machine is 1080p.

**Comment by TheElixZammuto** [comment]
Merging this on a lateral branch so GitHub actions can Run. Actual PR now should be #38

**Comment by lyndonguitar** [comment]
im just wondering it does say 4k is not working (pending) on the home page. 

however in the last version 1.10.0 (oct 2022) it does say 4k was added. just want to confirm which is more updated

i dont have an xbox yet to try but im going to buy next month, just looking out for the features ill use

**Pull request merged**
