### PR TITLE
Fix 4k render scale for Xbox Series S/ Xbox one S

### PR DESCRIPTION
**Pull request by seskid**

### CODE REVIEW

**Review by TheElixZammuto — COMMENTED** [review]
Quick Question: does the Composition Scale also depend on the host resolution? (if 4K or not on the Host side?)

**Comment by seskid** [comment]
> Quick Question: does the Composition Scale also depend on the host resolution? (if 4K or not on the Host side?)

Host resolution doesn't seem to matter here. Xbox resolution setting just needs to be 4k and not 1080p. If on 1080p users should leave this on normal.

**Review by TheElixZammuto — CHANGES_REQUESTED** [review]
I would prefer to move the General Settings like the composition scale on the general ApplicationState.h, alongside the margin settings e.g.

**Comment by seskid** [comment]
> I would prefer to move the General Settings like the composition scale on the general ApplicationState.h, alongside the margin settings e.g.

Sure sounds good, I'll work on moving it there.

**Comment by seskid** [comment]
> > I would prefer to move the General Settings like the composition scale on the general ApplicationState.h, alongside the margin settings e.g.
> 
> Sure sounds good, I'll work on moving it there.

This change been has been made. Dont have xbox one s to test unfortunately.

**Comment by joaopedrosgs** [comment]
Hey, is there any way to test this without compiling it from scratch?

**Comment by TheElixZammuto** [comment]
> Hey, is there any way to test this without compiling it from scratch?

@seskid can you confirm you did the changes requested? If so I can merge this over #38   and make a dev mode package ready

**Comment by seskid** [comment]
> > Hey, is there any way to test this without compiling it from scratch?
> 
> @seskid can you confirm you did the changes requested? If so I can merge this over #38 and make a dev mode package ready

Yes the changes requested have been made feel free to make a dev mode package.

**Review by TheElixZammuto — APPROVED** [review]

**Comment by TheElixZammuto** [comment]
On PC it seems to work as intended (as in resizing the viewport).

LGTM, thank you for your work!

**Pull request merged**
