### PR TITLE
Send data from all available gamepads

### PR DESCRIPTION
**Pull request by 3ap**
Looks like it works, I've tested it with two Xbox Series Controllers. Could someone test it too, please, before merging?

### CODE REVIEW

**Comment by 3ap** [comment]
I've found it doesn't work with Windows 7 + NVIDIA Geforce Experience: both gamepads control the first player in games, but it works perfectly in Windows 11. I hope, it would be possible to check it by anyone else after merging #12.

**Comment by TheElixZammuto** [comment]
I'm going to check this out after fixing the issues I'm working on. I have Sunshine + Windows 11, so it should be enough coverage to make sure it works correctly client side

**Comment by 3ap** [comment]
@TheElixZammuto friendly reminder

**Comment by TheElixZammuto** [comment]
Sorry for the late response, I'll test this in the following days!

**Comment by TheElixZammuto** [comment]
Tested it and it works as intended, thank you!

**Comment by cgutman** [comment]
You should also pass the gamepad mask to `gs_start_app()` to support games that don’t do gamepad hotplugging.

**Comment by TheElixZammuto** [comment]
Thanks for the Insight @cgutman, I'm posting this as an issue to track it later

**Pull request merged**
