### PR TITLE
Fix for high latency at the beginning of stream

### PR DESCRIPTION
**Pull request by MichaelMKenny**
As mentioned in issues #2 and #17.

### CODE REVIEW

**Comment by TheElixZammuto** [comment]
First of all, thank you for the PR!
Personally I haven't saw any changes in performance in this PR on my Xbox One, but it's probably has more effect on Xbox Series.
On which console have you tested this?

**Comment by TheElixZammuto** [comment]
I'm merging this so I can run the pipeline and make people test these changes

**Comment by MichaelMKenny** [comment]
Xbox Series X. 

I haven't been able to reproduce the high latency problem today, maybe since I downgraded GFE versions, but yesterday it was very repeatable, and this PR seemed to fix it. 

When problem was happening the latency would get better over time. 
The latency seemed to be better when I set the bitrate high, like 40-60Mbps. But when the bitrate was high I would get the video freezing-up, and playing back the last 3 frames (frame-queue length), though audio would continue. I could resume the video, by going to the Xbox dashboard, and back. 
At 20Mbps I didn't get the video freeze, but would get the high latency. This PR fixes it playing catchup with all the frames coming in, by dropping them so it's more responsive. 

I recently downgraded my Geforce Experience to a lower more-stable version, which doesn't seem to exhibit the high latency, but with the newer one, it was very much a problem. Sunshine didn't seem to have the problem. 
From what I can make out from this repo's issues, some people have the problem I was facing, so I hope this can help them :)

**Comment by TheElixZammuto** [comment]
Gotcha, since I only use Sunshine that's way I wasn't able to reproduce the problem

**Pull request merged**
